/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 2;
=======
const int buildversion = 5;
>>>>>>> 31dbd1a62c81b975375972401eabc04909095b6c
const char buildconfig[] = "ASST0";
